### ISSUE TITLE
Adding new alignment functions

### ISSUE THREAD

**Issue by memoryleine** [AllenCell/cvapipe_analysis#13]
Hi there, I posted on the Allen Cell forum about this and was told I should open an issue here for further discussion.

## Use Case
*Please provide a use case to help us understand your request in context*
In the cell variance paper on bioRxiv, it is noted that different methods of alignment can be used to generate different versions of shape space. Currently there is one method of alignment, `alignment_2d`, which aligns the cells along their long axis in the xy plane without changing the z-axis. While this seems to be a good method for the cell types studied in the paper, it would be good to have other functions available. Users could then test how changing alignment changes the shape space generated for the data from the paper or for their own datasets, and choose what is most ideal for what they would like to study.

## Solution
*Please describe your ideal solution*
Provide more options for the alignment and allow the user to choose the alignment method when running the pipeline (maybe via the configuration file?). I think ideally this should be done in a way that the method of alignment is recorded at the time of running the workflow to make it easy for users to compare the output of different alignment steps.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
Instead of providing more alignment functions _per se_, provide instructions for advanced users to be able to add their own alignment functions to the source code. I think this would be good to do whether or not more options for alignment are added right now because it is hard to predict all the possible ways someone might want to try aligning their cells.

This is maybe a far-off idea but I think it would be cool if the code could be updated whenever someone publishes a paper that uses a new alignment method and the documentation provided citations for each alignment method. I imagine new users could then browse the citations and choose an alignment method that they think would work best for their dataset. Based on my understanding so far, it seems the method of alignment is one of the biggest choices I need to make to optimize this pipeline for my own data. I have some ideas about what to try (can discuss further if there is interest) but I am still working on implementing them.

**Comment by vianamp** [comment]
Hi @memoryleine.

The underlaying package we use for alignment and SHE coefficients calculation is called `aics-shparam`. The function that calculates the spherical harmonics expansion in this package has a parameter (`alignment_2d`) that can be turned off to disable the alignment. As you notice however,  this is not exposed in the `cvapipe_analysis` package and therefore the user is forced to use the same alignment we use in the paper.

Do you think that would be enough for now to expose this parameter so the user can turn the alignment off? In that case, the user could apply any pre-alignment method to the images and save them. Then, with `alignment_2d=False`, `cvapipe_analysis` would calculate SHE coefficients on the images without applying any alignment.

Of course, we can also implement different alignment methods in `aics-shparam` and we plan to do so in the future.

Let me know your thoughts and thanks for the feedback.

**Comment by memoryleine** [comment]
Hi @vianamp, thanks for your response. I was wondering whether to post this here or in the `aics-shparam` repo since the `align_image_2d` function lives in that package, not this one. It makes sense that if new alignment functions are added, they would be added there. But for the time being, since I'm already developing my own alignment method(s) anyway, it is more useful to have a way to choose or turn off the alignment when running this pipeline, so I decided to post here instead.

Yes, I do think that making the alignment optional would work for the time being. Then, like you suggest, I could align the images beforehand using a script and run the feature extraction with the alignment disabled. That would make testing out different alignment methods easier and that is enough for me. In fact, I could probably make that change to my local copy myself. I brought this up mainly because I was curious if there were plans to eventually add that functionality and I thought that would be generally useful for future users. However, I realize that this probably isn't a priority right now, and I will clarify that I don't expect any changes to be made on your end to accommodate my current (probably earlier than anticipated) use of this package to do test runs of the methodology on my own dataset.

**Comment by vianamp** [comment]
Hi @memoryleine. I will expose a parameter for making the alignment optional. And yes, you are right. If we decide to add different alignment methods in the future that would be in the `aics-shparam` repo.

- [ ]  **Expose parameter for making images alignment optional. Also include this in the config YAML file.**

**Comment by vianamp** [comment]
Hi @memoryleine. With the recent PR you are able to turn the alignment off in the config file by setting 

```
features:
    align:
        reference: off
        unique: off
```
Let me know if you have more question. Closing this issue for now.

**Comment by memoryleine** [comment]
Thanks, much appreciated!
