### ISSUE TITLE
Compute features step fails on single channel images

### ISSUE THREAD

**Issue by memoryleine** [AllenCell/cvapipe_analysis#30]
## Description
When using my own dataset of single channel images, compute features fails for all cells. Specifically, line 76 in `compute_features_tools.py` throws ValueError: not enough values to unpack (expected 3, got 2).

The issue seems to originate from line 40 of io.py:

`img = AICSImage(path).data.squeeze()`

For the case of single channel images, the C dimension is a singleton, so it is probably getting thrown out by `squeeze()`. Then later, when the image data is subset by chId, the Z dimension is thrown out instead of the C dimension, resulting in the "not enough values to unpack" error.

Changing this line to the following in my local copy fixes the problem for me.

`reader = AICSImage(path)`
`img = reader.get_image_data('CZYX', S=0, T=0)`

**Comment by vianamp** [comment]
Thank you. I will add your patch to the code.
