### ISSUE TITLE
Update Request for README

### ISSUE THREAD

**Issue by Visytudz** [AllenCell/cvapipe_analysis#51]
Hello,

Firstly, I'd like to commend the team on this fantastic open-source project! I've noticed the numerous optimizations and iterations that have been made recently, which are greatly appreciated.

However, I've observed that the README seems to be a bit outdated in comparison. For instance, the build environment instructions in the README still reference `conda create --name cvapipe python=3.8`, but the latest version of the project now requires Python 3.9. Additionally, the README mentions a configuration file named config.yaml that needs to be set up, but I couldn't find this file in the current project structure. Has it been merged elsewhere or replaced with another configuration method?

Thank you for your attention to this matter, and I look forward to seeing the README updated to reflect the project's latest state.

**Comment by vianamp** [comment]
Hi @Visytudz. Thank you for your interest in using `cvapipe_analysis`. As you noticed, we are in process of refactoring this codebase to make it easier to reproduce figures in the paper but also make its functionalities more reusable across different projects we work on. We are working on updating the README file soon. In the meantime, I encourage you to use the master branch at commit `c6c0ca3` which is in agreement with the current README. Let me know if there is anything I can assist you with in the meantime.

**Comment by Visytudz** [comment]
Ok! Thanks for the information.
