### ISSUE TITLE
Aggregation step issue?

### ISSUE THREAD

**Issue by abbyscience** [AllenCell/cvapipe_analysis#67]
Hello! I am trying to aggregate PILRs from ~800 cells into just one average shape. I've gotten everything through parameterization working OK, but when I run aggregation, the aggregation folder is formed, but no images in the subfolders. I've added a screenshot of the error-- "AttributeError: 'DataFrame' object has no attribute 'append'" (in the shapespace function), and a copy of my config and manifest files! User error maybe?

<img width="1239" alt="Screenshot 2024-05-23 at 1 02 44 PM" src="https://github.com/AllenCell/cvapipe_analysis/assets/116041812/56197af5-3076-4923-9e2a-c36063e7135c">

[manifest.csv](https://github.com/AllenCell/cvapipe_analysis/files/15422109/manifest.csv)

[config_copy.txt](https://github.com/AllenCell/cvapipe_analysis/files/15422111/config_copy.txt)

**Comment by vianamp** [comment]
Please trying downgrading your Pandas version to 1.4.0. Let me know if works.

**Comment by abbyscience** [comment]
Yes, that was it, thanks a bunch!!
