### ISSUE TITLE
Custom input dataset

### ISSUE THREAD

**Issue by vianamp** [AllenCell/cvapipe_analysis#7]
Adjust the step `load_data` to be able to load a custom dataset. This requires:
- Collect all the information used for all steps, e.g. path for segmentation and raw data, channels names, names of tagged structure(s) and so on.
- Take into account that each step requires only certain information. So depending on the input the user can run steps A and C but not B.
- Creating a function that validates whether all the information required for all steps are available in the custom CSV file.

**Comment by pushkarsathe89** [comment]
Hi,

Is this feature available? I would like to test on pre-segmented images. Also, can images with hundreds of cells be handled?

Thanks,
Best,
Pushkar

**Comment by vianamp** [comment]
Hi Pushkar.

We are working on this feature right now. It should be done in a few days I will let you know here.

Also, only single cell images can be used as input. Therefore, you would have to crop each cell out of your image and save them as individual files.

Best

**Comment by pushkarsathe89** [comment]
Hi Matheus,

Thanks. Looking forward to it. 

Ah ok. I can separate individual cells once they are segmented and use them as input. 

Best,
Pushkar

**Comment by vianamp** [comment]
Custom 3D datasets are addressed by this PR. Closing this issue.
